services:
  db:
    image: postgres:15
    container_name: postgresql_main
    restart: no
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:7
    container_name: redis_main
    restart: no
    volumes:
      - redis_data:/data
    networks:
      - backend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_main
    restart: no
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    command: >
      sh -c "
      until nc -z $${POSTGRES_HOST} $${POSTGRES_PORT}; do
        echo '‚è≥ Waiting for Postgres...';
        sleep 2;
      done &&
      python manage.py migrate &&
      python manage.py init_setup && 
      python manage.py collectstatic --noinput &&
      python manage.py runserver $${UVICORN_HOST}:$${UVICORN_PORT}
      "
    volumes:
      - .:/code
      - ./static:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - db
      - redis
    ports:
      - "${UVICORN_PORT:-8000}:${UVICORN_PORT:-8000}"
    networks:
      - backend
  nginx:
    image: nginx:1.27
    container_name: nginx_main
    restart: no
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
